CREATE TABLE IF NOT EXISTS drivers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    license_number VARCHAR(20) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    CONSTRAINT drivers_status_check CHECK (status IN ('active', 'inactive', 'leave'))
);

CREATE TABLE IF NOT EXISTS vehicles (
    id INTEGER PRIMARY KEY,
    plate VARCHAR(10) NOT NULL UNIQUE,
    model VARCHAR(100) NOT NULL,
    driver_id INTEGER NOT NULL UNIQUE REFERENCES drivers(id),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS vehicles_driver_id_idx ON vehicles(driver_id);
